In [1]:
import torch
import numpy as np

# Tensor and basic operations

In [2]:
torch.Tensor(5, 4)

tensor([[ 0.0000e+00,  0.0000e+00,  9.9815e-30,  1.4013e-45],
        [-5.6035e-30,  4.5757e-41, -5.6035e-30,  4.5757e-41],
        [-5.6035e-30,  4.5757e-41,  9.7484e-30,  1.4013e-45],
        [ 9.5336e-27,  1.4013e-45,  0.0000e+00,  0.0000e+00],
        [-5.6036e-30,  4.5757e-41,  0.0000e+00,  0.0000e+00]])

In [3]:
torch.rand(5, 4)

tensor([[0.6599, 0.9840, 0.4383, 0.9589],
        [0.6367, 0.1991, 0.5660, 0.9288],
        [0.4850, 0.9510, 0.3719, 0.4953],
        [0.6350, 0.4710, 0.4984, 0.8323],
        [0.3098, 0.9949, 0.3227, 0.8446]])

In [4]:
a = torch.rand(3, 2)
a.size()

torch.Size([3, 2])

In [5]:
# similar function in numpy
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# tensor to numpy array
a = torch.rand(3, 2)
print(a.numpy())

[[0.9458454  0.22554964]
 [0.40363842 0.52600515]
 [0.37634945 0.70645356]]


In [7]:
# numpy array to tensor
a = np.array([[3, 5], [2, 7]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 5],
        [2, 7]])


In [8]:
# operations are similar with numpy
x = torch.rand(3, 2)
y = torch.rand(3, 2)
c = 3

In [9]:
print(c * x)

tensor([[1.9594, 1.9012],
        [1.0157, 0.4396],
        [1.3204, 2.7126]])


In [10]:
print(x + y)

tensor([[0.7604, 1.5318],
        [1.2856, 0.8762],
        [0.4875, 1.1397]])


In [11]:
print(x.add(y))

tensor([[0.7604, 1.5318],
        [1.2856, 0.8762],
        [0.4875, 1.1397]])


In [12]:
# value changed addition operation
print(x)
x.add_(y)
print(x)

tensor([[0.6531, 0.6337],
        [0.3386, 0.1465],
        [0.4401, 0.9042]])
tensor([[0.7604, 1.5318],
        [1.2856, 0.8762],
        [0.4875, 1.1397]])


In [13]:
# gpu check
torch.cuda.is_available()

False

In [14]:
a = torch.rand(3, 2)
# a = a.cuda()
print(a)

tensor([[0.7441, 0.4505],
        [0.7668, 0.2372],
        [0.9878, 0.9805]])


### Auto derivation and Variable
![x.png](http://upload-images.jianshu.io/upload_images/3623720-1c2694b72e0341ce.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

In [15]:
from torch.autograd import Variable

In [16]:
# requires_grad -> requires derivation or not
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4
z

tensor([15.], grad_fn=<AddBackward0>)

In [17]:
# do deriavations for x and y respectively
z.backward()
z

tensor([15.], grad_fn=<AddBackward0>)

In [18]:
# derivations of z to x and z to y
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([2.])
dz/dy: tensor([1.])


### Neural network
torch.nn -> includes all opeartions of a neural network

torch.nn.functional -> dedicate a forward operation

In [19]:
from torch import nn
import torch.nn.functional as F

In [20]:
# a general network template
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # a simple convolutional layer
        self.conv1 = nn.Conv2d(3, 10, 3)

    def forward(self, x):
        # forward propagation
        out = self.conv1(x)
        return out