In [1]:
import torch
import numpy as np

# Tensor and basic operations

In [2]:
torch.Tensor(5, 4)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00, -2.5244e-29],
        [ 2.6327e+23,  2.7376e+20,  1.8040e+28,  1.8750e-19],
        [ 7.3909e+22,  2.4176e-12,  2.6209e+20,  4.1641e+12],
        [ 8.9625e-01,  7.9309e+34,  7.9439e+08,  3.2604e-12],
        [ 7.3113e+34,  9.5492e-01,  7.3154e+34,  5.9682e-02]])

In [3]:
torch.rand(5, 4)

tensor([[0.9352, 0.0396, 0.1702, 0.5114],
        [0.0934, 0.6657, 0.6984, 0.7684],
        [0.2188, 0.7358, 0.9705, 0.8681],
        [0.6791, 0.3387, 0.5471, 0.3631],
        [0.1706, 0.6383, 0.6166, 0.9823]])

In [4]:
a = torch.rand(3, 2)
a.size()

torch.Size([3, 2])

In [5]:
# similar function in numpy
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# tensor to numpy array
a = torch.rand(3, 2)
print(a.numpy())

[[0.72000945 0.9093255 ]
 [0.5675398  0.10503668]
 [0.5885989  0.00288606]]


In [7]:
# numpy array to tensor
a = np.array([[3, 5], [2, 7]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 5],
        [2, 7]])


In [8]:
# operations are similar with numpy
x = torch.rand(3, 2)
y = torch.rand(3, 2)
c = 3

In [9]:
print(c * x)

tensor([[0.8525, 1.0622],
        [2.9254, 0.1123],
        [0.9466, 1.2213]])


In [10]:
print(x + y)

tensor([[0.7343, 1.0594],
        [1.7316, 0.1668],
        [0.8212, 1.1892]])


In [11]:
print(x.add(y))

tensor([[0.7343, 1.0594],
        [1.7316, 0.1668],
        [0.8212, 1.1892]])


In [12]:
# value changed addition operation
print(x)
x.add_(y)
print(x)

tensor([[0.2842, 0.3541],
        [0.9751, 0.0374],
        [0.3155, 0.4071]])
tensor([[0.7343, 1.0594],
        [1.7316, 0.1668],
        [0.8212, 1.1892]])


In [13]:
# gpu check
torch.cuda.is_available()

False

In [14]:
a = torch.rand(3, 2)
# a = a.cuda()
print(a)

tensor([[0.8888, 0.5407],
        [0.9693, 0.1708],
        [0.3025, 0.4189]])


### Auto derivation and Variable
![x.png](http://upload-images.jianshu.io/upload_images/3623720-1c2694b72e0341ce.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

In [15]:
from torch.autograd import Variable

In [16]:
# requires_grad -> requires derivation or not
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4
z

tensor([15.], grad_fn=<AddBackward0>)

In [17]:
# do deriavations for x and y respectively
z.backward()
z

tensor([15.], grad_fn=<AddBackward0>)

In [18]:
# derivations of z to x and z to y
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([2.])
dz/dy: tensor([1.])


### Neural network
torch.nn -> includes all opeartions of a neural network

torch.nn.functional -> dedicate a forward operation

In [19]:
from torch import nn
import torch.nn.functional as F

In [20]:
# a general network template
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # a simple convolutional layer
        self.conv1 = nn.Conv2d(3, 10, 3)

    def forward(self, x):
        # forward propagation
        out = self.conv1(x)
        return out